apiversion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-namespace

resources:
  - nginx-namespace.yaml
  - deployments/nginx-deployment-a.yaml
  - deployments/nginx-deployment-b.yaml
  - services/nginx-service-a.yaml
  - services/nginx-service-b.yaml
  - nginx-ingress.yaml

configMapGenerator:
  - name: nginx-html-template-a
    files:
    - configmaps/index-a.html
  - name: nginx-html-template-b
    files:
    - configmaps/index-b.html

patches:
  - target:
      kind: Deployment
      name: nginx-deployment-a
    patch: |-
      - op: add
        path: /spec/selector/matchLabels/app
        value: nginx-a
      - op: add 
        path: /spec/template/metadata/labels/app
        value: nginx-a
    
  - target:
      kind: Deployment
      name: nginx-deployment-b
    patch: |-
      - op: add 
        path: /spec/selector/matchLabels/app
        value: nginx-b
      - op: add
        path: /spec/template/metadata/labels/app
        value: nginx-b
  
  - target:
      kind: Service
      name: nginx-service-a
    patch: |-
      - op: add
        path: /spec/selector/app
        value: nginx-a

  - target:
      kind: Service
      name: nginx-service-b
    patch: |-
      - op: add
        path: /spec/selector/app
        value: nginx-b