apiversion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-namespace

commonLabels:
  app: nginx

resources:
  - nginx-namespace.yaml
  - deployments/nginx-deployment-a.yaml
  - deployments/nginx-deployment-b.yaml
  - services/nginx-service-a.yaml
  - services/nginx-service-b.yaml
  - nginx-ingress.yaml

configMapGenerator:
  - name: nginx-html-template-a
    files:
    - configmaps/index-a.html
  - name: nginx-html-template-b
    files:
    - configmaps/index-b.html