apiversion: kustomize.config.k8s.io/v1
kind: Kustomization

namespace: nginx-namespace

commonLabels:
  app: nginx

resources:
  - nginx-namespace.yaml
  - deployments/
  - services/
  - nginx-ingress-controller.yaml
  - nginx-ingress.yaml

configMapGenerator:
  - name: nginx-html-template-a
    files:
    - configmaps/index-a.html
  - name: nginx-html-template-b
    files:
    - configmaps/index-b.html