controller:
  name: controller
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
  ingressClass: nginx
  replicaCount: 2
  nodeSelector: {}
  tolerations: {}
  affinity: {}

  service:
    enabled: true
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      service.beta.kubernetes.io/azure-load-balancer-internal-ip: "10.10.1.7"
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"
      service.beta.kubernetes.io/port_80_health-probe-protocol: "HTTP"
      service.beta.kubernetes.io/port_443-health-probe-protocol: "HTTPS"
    externalTrafficPolicy: Local
    ports:
      http: 80
      https: 443
  
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
  
  defaultBackend:
    enabled: false
