apiVersion: v1
kind: Service
metadata:
  name: nginx-service-a
  labels:
    app: nginx-a
spec:
  selector:
    app: nginx-a
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP